<a href="https://colab.research.google.com/github/abdelrhmanhesham1/python-challenges/blob/main/S1_Preprocessing_%26_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Arrays

Creating a 1D Numpy Array from a List

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # Output: [1 2 3 4 5]


[1 2 3 4 5]


Creating a 2D Numpy Array from a List of Lists

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)  # Output: [[1 2 3]
             #          [4 5 6]]

[[1 2 3]
 [4 5 6]]


Creating an Array of Zeros

In [4]:
zeros = np.zeros((2, 3))
print(zeros)  # Output: [[0. 0. 0.]
              #          [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


Creating an Array of Ones

In [5]:
ones = np.ones((3, 2))
print(ones)  # Output: [[1. 1.]
             #          [1. 1.]
             #          [1. 1.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


Creating an Array with a Specific Range

In [6]:
range_array = np.arange(10)
print(range_array)  # Output: [0 1 2 3 4 5 6 7 8 9]


[0 1 2 3 4 5 6 7 8 9]


Creating an Array with a Range of Values and Specific Step Size

In [7]:
range_step = np.arange(0, 10, 2)
print(range_step)  # Output: [0 2 4 6 8]


[0 2 4 6 8]


Creating an Array of Evenly Spaced Values Between Two Numbers

In [8]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)  # Output: [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


Creating an Array with Random Values Between 0 and 1


In [9]:
random_array = np.random.rand(3, 3)
print(random_array)


[[0.21945227 0.32852326 0.53214781]
 [0.6814448  0.81245541 0.93337112]
 [0.95063732 0.08383665 0.24471046]]


Creating an Array with Random Integers

In [10]:
random_integers = np.random.randint(1, 10, (2, 2))
print(random_integers)


[[8 9]
 [7 1]]


Checking the Shape of an Array

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)


(2, 3)


Accessing Data Type of Elements

In [12]:
print(arr.dtype)  # Output: int64

int64


Indexing a 1D Array

In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Output: 10
print(arr[-1])  # Output: 50


10
50


Slicing a 1D Array

In [14]:
print(arr[1:4])  # Output: [20 30 40]


[20 30 40]


Indexing a 2D Array

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 2])  # Output: 3


3


Slicing a 2D Array

In [16]:
print(arr[1:, 1:])  # Output: [[5 6]
                    #          [8 9]]


[[5 6]
 [8 9]]


Element-wise Addition

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Output: [5 7 9]


[5 7 9]


Array Broadcasting

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10)  # Output: [[11 12 13]
                 #          [14 15 16]]


[[11 12 13]
 [14 15 16]]


Matrix Multiplication

In [19]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr1, arr2))  # Output: [[19 22]
                           #          [43 50]]


[[19 22]
 [43 50]]


Calculating Mean and Sum

In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0
print(np.sum(arr))   # Output: 15


3.0
15


Finding Maximum and Minimum Values

In [21]:
print(np.max(arr))  # Output: 5
print(np.min(arr))  # Output: 1


5
1


# Practical Applications

Square Matrix

In [22]:
import numpy as np

square_matrix = np.array([[1, 2, 3],
                          [4, 2, 6],
                          [7, 8, 9]])
print("Square Matrix:\n", square_matrix)


Square Matrix:
 [[1 2 3]
 [4 2 6]
 [7 8 9]]


Diagonal Matrix

In [23]:
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal_matrix)


Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


Identity Matrix

In [24]:
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Upper Triangular Matrix

In [25]:
upper_triangular = np.array([[1, 2, 3],
                             [0, 5, 6],
                             [0, 0, 9]])
print("Upper Triangular Matrix:\n", upper_triangular)


Upper Triangular Matrix:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


Lower Triangular Matrix

In [26]:
lower_triangular = np.array([[1, 0, 0],
                             [4, 5, 0],
                             [7, 8, 9]])
print("Lower Triangular Matrix:\n", lower_triangular)


Lower Triangular Matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


Symmetric Matrix

In [27]:
symmetric_matrix = np.array([[1, 2, 3],
                             [2, 5, 6],
                             [3, 6, 9]])
print("Symmetric Matrix:\n", symmetric_matrix)


Symmetric Matrix:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]


Transpose of a Matrix

In [28]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
transpose_matrix = np.transpose(matrix)
print("Matrix:\n", matrix)
print("Transpose of Matrix:\n", transpose_matrix)


Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose of Matrix:
 [[1 4]
 [2 5]
 [3 6]]


Trace of a Matrix

In [29]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
trace = np.trace(matrix)
print("Trace of Matrix:", trace)


Trace of Matrix: 15


Determinant of a Matrix

In [30]:
matrix = np.array([[4, 6],
                   [3, 8]])
determinant = np.linalg.det(matrix)
print("Determinant of Matrix:", determinant)


Determinant of Matrix: 14.000000000000004


Inverse of a Matrix

In [31]:
matrix = np.array([[1, 2],
                   [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of Matrix:\n", inverse_matrix)


Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Rank of a Matrix

In [32]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
rank = np.linalg.matrix_rank(matrix)
print("Rank of Matrix:", rank)


Rank of Matrix: 2
